import { Workspace, SEASONS, TEAMS } from "./model";
let n = 10;
const id = () => `00000000-0000-4000-8000-${String(n++).padStart(12, "0")}`;
const b = (season = SEASONS[0].id) => ({
  id: id(),
  version: 1,
  season_id: season,
  archived: false,
  updated_at: "2026-10-01T09:00:00Z",
});
export function createMock(): Workspace {
  n = 10;
  const sponsors = [
    "North Sails",
    "Gurit",
    "B&G Marine",
    "OneSails",
    "RINA",
    "Persico Marine",
    "Sicomin",
    "Ocean Materials",
  ].map((title, i) => ({
    ...b(),
    title,
    type: i % 3 === 0 ? "Finanziario" : i % 3 === 1 ? "Tecnico" : "Ibrido",
    stage: [
      "Attivo",
      "In trattativa",
      "Contatto avviato",
      "Contratto",
      "Da contattare",
    ][i % 5],
    contact: "Referente partnership (demo)",
    email: "",
    amount_cents: i % 3 === 1 ? 0 : [250000, 0, 150000, 200000, 0][i % 5],
    technical_cents: i % 3 ? 180000 : 0,
    next_action: [
      "Organizzare contenuto dedicato",
      "Inviare proposta tecnica",
      "Follow-up presentazione",
      "Raccogliere firma",
      "Preparare primo contatto",
    ][i % 5],
    due_date: `2026-10-${String(5 + i * 2).padStart(2, "0")}`,
    notes: "Trattativa dimostrativa. Nessun contatto effettuato.",
    pitch_url: "",
    document_url: "",
    activities: [
      { at: "2026-10-01T09:00:00Z", text: "Trattativa dimostrativa creata." },
    ],
  }));
  const events = [
    {
      ...b(),
      title: "Presentazione della stagione",
      type: "Presentazione",
      status: "In preparazione",
      date: "2026-10-16",
      location: "Sapienza · Roma",
      description:
        "Raccontiamo il progetto Meravijosa e gli obiettivi della nuova stagione.",
      checklist: [
        "Definire programma",
        "Preparare presentazione",
        "Confermare spazio",
        "Invitare partner",
        "Organizzare materiali media",
      ].map((title, i) => ({ id: id(), title, done: i < 2 })),
      sponsor_id: "",
      document_url: "",
      recap: "",
    },
    {
      ...b(),
      title: "Giornata in cantiere",
      type: "Evento team",
      status: "Confermato",
      date: "2026-10-24",
      location: "Cantiere · Bracciano",
      description: "Una giornata di lavoro e contenuti con il team.",
      checklist: [
        "Organizzare trasporti",
        "Preparare attrezzatura",
        "Briefing sicurezza",
      ].map((title, i) => ({ id: id(), title, done: i === 0 })),
      sponsor_id: "",
      document_url: "",
      recap: "",
    },
  ];
  return {
    sponsors,
    events,
    links: [
      ["Sito del team", "https://sapienzafoilingteam.com", "Team"],
      [
        "Gmail del team",
        "https://mail.google.com/mail/u/?authuser=sapienzafoilingteam@gmail.com",
        "Team",
      ],
      ["Drive media", "", "Media"],
      ["Instagram", "https://www.instagram.com/sapienzafoilingteam/", "Media"],
      ["SuMoth deliveries", "", "SuMoth"],
      ["Pitch e presentazioni", "", "Media"],
    ].map(([title, url, category]) => ({
      ...b(),
      title,
      url,
      category,
      team_id: "",
    })),
    pages: TEAMS.map((t, i) => ({
      ...b(),
      team_id: t.id,
      summary: [
        "Definizione della geometria e revisione dello scafo.",
        "Prepariamo la stagione, le partnership e il racconto del team.",
        "Analisi dei materiali e obiettivi di sostenibilità.",
        "Pianificazione delle lavorazioni e del cantiere.",
        "Studio dei profili e controllo dell’assetto.",
        "Preparazione acquisizione dati e telemetria.",
        "Pianificazione della logistica per test ed eventi.",
      ][i],
      blocks: [
        { id: id(), type: "titolo", content: "Obiettivi della stagione" },
        {
          id: id(),
          type: "checklist",
          content: [
            "Completare la revisione del progetto",
            "Aggiornare pitch e media kit",
            "Confrontare soluzioni a minore impatto",
            "Preparare il piano di produzione",
            "Validare i profili in simulazione",
            "Testare il sistema di acquisizione",
            "Definire il piano trasporti",
          ][i],
          checked: false,
        },
        {
          id: id(),
          type: "checklist",
          content: "Preparare il report mensile",
          checked: false,
        },
        { id: id(), type: "titolo", content: "Cosa stiamo facendo" },
        {
          id: id(),
          type: "testo",
          content:
            t.description +
            " Questa pagina è uno spazio condiviso: aggiungi aggiornamenti, obiettivi e risorse.",
        },
        {
          id: id(),
          type: "richiamo",
          content:
            "I contenuti iniziali sono esempi. Personalizzali con il lavoro del reparto.",
        },
        { id: id(), type: "titolo", content: "Risorse del reparto" },
        { id: id(), type: "link", content: "Drive del reparto", url: "" },
        { id: id(), type: "link", content: "Riunione del reparto", url: "" },
      ],
      revisions: [],
    })),
    reports: TEAMS.slice(0, 3).map((t, i) => ({
      ...b(),
      team_id: t.id,
      title: [
        "Revisione geometria dello scafo",
        "Il punto sulla nuova stagione",
        "Materiali: primi confronti",
      ][i],
      content:
        "Abbiamo raccolto le prime osservazioni e definito i prossimi passi. Report dimostrativo, da sostituire con un aggiornamento reale.",
      date: "2026-10-01",
      url: "",
    })),
    deliveries: [
      ["Report mensile SuMoth", "Report", "2026-10-10", "In preparazione"],
      ["Dietro le quinte: il cantiere", "Instagram", "2026-10-12", "Da fare"],
      ["Diario di bordo · ottobre", "Blog post", "2026-10-20", "Da fare"],
      [
        "Post presentazione stagione",
        "Instagram",
        "2026-10-16",
        "Da verificare",
      ],
    ].map(([title, type, date, status]) => ({
      ...b(),
      title,
      type,
      date,
      status,
      team_id: "management",
      priority: "Media",
      url: "",
      notes: "Delivery dimostrativa.",
      completion_url: "",
      completed_at: "",
      recurrence_key: null,
    })),
    costs: [
      ["Tessuti e resina per test", 12000, "Materiali", "materiali"],
      ["Trasporto attrezzatura", 8000, "Logistica", "shore"],
      ["Componenti acquisizione dati", 16550, "Elettronica", "elettronica"],
      ["Stampa materiali evento", 4500, "Comunicazione", "management"],
    ].map(([title, amount_cents, category, team_id]) => ({
      ...b(),
      title: String(title),
      amount_cents: Number(amount_cents),
      category: String(category),
      team_id: String(team_id),
      date: "2026-10-01",
      event_id: "",
      vendor: "Fornitore dimostrativo",
      paid_by: "Team",
      document_url: "",
      notes: "",
    })),
    contracts: [
      {
        ...b(),
        title: "Partnership · OneSails",
        versions: [],
        sponsor_id: sponsors[3].id,
        event_id: "",
        type: "Sponsor tecnico",
        status: "Bozza",
        date: "2026-10-01",
        url: "",
        notes: "Documento dimostrativo: inserire un modello validato dal team.",
      },
    ],
    templates: [
      [
        "Primo contatto sponsor",
        "Sponsor",
        "Sapienza Foiling Team × {azienda}",
        "Buongiorno {nome_contatto},\n\nsiamo il Sapienza Foiling Team, il team studentesco che progetta e costruisce Meravijosa per la SuMoth Challenge.\n\nCi piacerebbe presentarvi il progetto e valutare una collaborazione con {azienda}. Qui trovate una breve presentazione: {link_pitch}.\n\nPossiamo organizzare un incontro conoscitivo?\n\nGrazie,\nSapienza Foiling Team",
      ],
      [
        "Follow-up proposta",
        "Sponsor",
        "Un aggiornamento sulla proposta per {azienda}",
        "Buongiorno {nome_contatto},\n\ntorno a scrivervi riguardo alla proposta di collaborazione. Siamo disponibili per chiarire i dettagli e concordare i prossimi passi.\n\nGrazie,\nSapienza Foiling Team",
      ],
      [
        "Invito a un evento",
        "Eventi",
        "Invito · {evento}",
        "Buongiorno {nome_contatto},\n\nvi invitiamo a {evento}, in programma il {data}. Sarà un’occasione per conoscere il team e il progetto.\n\nDettagli: {link_evento}\n\nSapienza Foiling Team",
      ],
      [
        "Invio contratto",
        "Contratti",
        "Accordo di collaborazione · {azienda}",
        "Buongiorno {nome_contatto},\n\ncondividiamo il documento per la collaborazione: {link_contratto}.\nRestiamo a disposizione per un confronto sui contenuti.\n\nSapienza Foiling Team",
      ],
      [
        "Presentazione del team",
        "Presentazioni",
        "Conosci il Sapienza Foiling Team",
        "Buongiorno {nome_contatto},\n\nprogettiamo, costruiamo e portiamo in regata un Moth foiling sostenibile.\nScopri il nostro progetto: {link_pitch}\n\nSapienza Foiling Team",
      ],
      [
        "Richiesta materiali media",
        "Media",
        "Materiali per raccontare la collaborazione",
        "Buongiorno {nome_contatto},\n\nper preparare i contenuti della collaborazione con {azienda}, potete condividere logo e indicazioni d’uso?\n\nGrazie,\nSapienza Foiling Team",
      ],
    ].map(([title, category, subject, body]) => ({
      ...b(),
      title,
      category,
      subject,
      body,
      url: "",
    })),
    offers: [
      [
        "Visibilità sulla barca",
        "Presenza del marchio sulla barca e nei materiali del team.",
        "Spazi e applicazione da concordare; verificare regolamenti e uso dei marchi.",
      ],
      [
        "Contenuti e storytelling",
        "Raccontare la collaborazione con post, foto e contenuti dedicati.",
        "Definire quantità, canali, calendario e approvazione dei contenuti.",
      ],
      [
        "Eventi insieme",
        "Presentazioni del progetto e incontri tra partner e studenti.",
        "Verificare luogo, disponibilità barca, logistica e calendario.",
      ],
    ].map(([title, description, conditions]) => ({
      ...b(),
      title,
      description,
      conditions,
    })),
    documents: [
      ["Pitch generale", "Presentazioni"],
      ["Media kit", "Media"],
      ["Loghi ufficiali", "Identità"],
      ["Modello sponsor finanziario", "Contratti"],
      ["Modello sponsor tecnico / ibrido", "Contratti"],
      ["Modello evento congiunto", "Contratti"],
    ].map(([title, category]) => ({
      ...b(),
      title,
      category,
      url: "",
      storage_path: "",
    })),
    recurrences: [
      ["Report mensile SuMoth", "Report", 10],
      ["Blog post mensile", "Blog post", 20],
      ["Post Instagram mensile", "Instagram", 25],
    ].map(([title, type, day]) => ({
      ...b(),
      title: String(title),
      type: String(type),
      day: Number(day),
      team_id: "management",
      priority: "Media",
    })),
  };
}
